sudo    : false
language: cpp

compiler:
  - gcc
  - clang

env:
  global:
    - LD_LIBRARY_PATH="${TRAVIS_BUILD_DIR}/lib:${LD_LIBRARY_PATH}"
    - CXXFLAGS="-g"

before_install:
  - pip install --user cpp-coveralls
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then brew update; fi

install:
  - if [ "${CXX}" != "clang++" ]; then CXXFLAGS+=" --coverage"; fi

script:
  - cd ${TRAVIS_BUILD_DIR}
  - make
  - make test
  - cd parser_sandbox
  - make
  - make test

after_success:
  - cd ${TRAVIS_BUILD_DIR}
  - coveralls
    --include include
    --include src
    --exclude tests
    --exclude lib
    --exclude include/occa/operators
    --exclude src/operators
    --exclude-pattern '.*\.h(pp)?$'
    --exclude-pattern '.*/(cuda|opencl|openmp|threads)/.*'
    --exclude-pattern '.*/lang/(fortran|python)/.*'
    --gcov-options '\-lp'

notifications:
  email: false
