sudo:     false
language: cpp

compiler:
  - gcc
  - clang

env:
  global:
    - LD_LIBRARY_PATH="${TRAVIS_BUILD_DIR}/lib:${LD_LIBRARY_PATH}"
    - CXXFLAGS="-g"

before_install:
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then brew update; fi

install:
  - |
    if [ "${CXX}" != "clang++" ]; then
      CXXFLAGS+=" -fprofile-arcs -ftest-coverage -lgcov"
    fi

script:
  - cd ${TRAVIS_BUILD_DIR}
  - make
  - make test
  - cd parser_sandbox
  - make
  - make test

after_success:
  - |
    if [ "${CXX}" != "clang++" ]; then
      cd ${TRAVIS_BUILD_DIR}
      bash <(curl -s https://codecov.io/bash)
    fi

notifications:
  email: false
